In [1]:
import numpy as np

In [2]:
a = np.array([1,2,4])
print(a)

[1 2 4]


In [3]:
two_d = np.array([[1,2,3],[4,5,6]])
print(two_d)

[[1 2 3]
 [4 5 6]]


In [4]:
#Get Dimension
a.ndim

1

In [5]:
#Get Shape
print(a.shape)
print(two_d.shape)

(3,)
(2, 3)


In [6]:
#Get Type
a.dtype
two_d.dtype

dtype('int32')

In [7]:
a = np.array([1,2,3],dtype = 'int16')
print(a)
a.dtype

[1 2 3]


dtype('int16')

In [8]:
#Get Size
a.itemsize          #int16  

2

In [9]:
#Get Total size
# a.size*a.itemsize
a.nbytes

6

In [10]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [11]:
a.shape

(2, 7)

In [12]:
#Get a specific elemnet [r,c]: 
a[1,3]

11

In [13]:
#Get specific row
a[0,:] 

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
#Get a specific col
a[:,3]

array([ 4, 11])

In [15]:
a[0,2:7:2]

array([3, 5, 7])

In [16]:
a[1,4]
a[1,4]= 19
print(a)



[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 19 13 14]]


In [17]:
#initializing different types of arrays

#All zeros matrix

np.zeros(4) 

#All ones matrix

np.ones((8,3))


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
#Any other number

np.full((2,3),88)

array([[88, 88, 88],
       [88, 88, 88]])

In [19]:
np.random.rand(2,3)

array([[0.56063894, 0.21849125, 0.42192391],
       [0.01678769, 0.24447416, 0.7249264 ]])

In [20]:
#Random Integer values

np.random.randint(6,size=(3,4))

array([[3, 3, 3, 2],
       [5, 4, 1, 3],
       [4, 2, 2, 2]])

In [22]:
var = np.random.rand(5)
print(var)
var

[0.94775798 0.33971714 0.70244564 0.57672636 0.78233789]


array([0.94775798, 0.33971714, 0.70244564, 0.57672636, 0.78233789])

In [23]:
var1 = np.random.rand(2,5)
var1

array([[0.85762752, 0.80711665, 0.97460895, 0.80360251, 0.57484381],
       [0.27585571, 0.89322162, 0.08459232, 0.53490799, 0.24438765]])

In [26]:
var2 = np.random.randint(0, 20,5)
var2

array([ 1, 10,  2,  2,  1])

In [31]:
a = np.array([1,2,3,4,5],dtype=np.int8)
print(a.dtype)

int8


In [32]:
#arithmetic operation
var=np.array([1,2,3,4,5])
var_add = var+3
print(var_add)


[4 5 6 7 8]
