In [1]:
import numpy as np

In [7]:
a = np.array([1,2,4])
print(a)

[1 2 4]


In [9]:
two_d = np.array([[1,2,3],[4,5,6]])
print(two_d)

[[1 2 3]
 [4 5 6]]


In [10]:
#Get Dimension
a.ndim

1

In [13]:
#Get Shape
print(a.shape)
print(two_d.shape)

(3,)
(2, 3)


In [15]:
#Get Type
a.dtype
two_d.dtype

dtype('int32')

In [19]:
a = np.array([1,2,3],dtype = 'int16')
print(a)
a.dtype

[1 2 3]


dtype('int16')

In [21]:
#Get Size
a.itemsize          #int16  

2

In [23]:
#Get Total size
# a.size*a.itemsize
a.nbytes

6

In [26]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [27]:
a.shape

(2, 7)

In [29]:
#Get a specific elemnet [r,c]: 
a[1,3]

11

In [30]:
#Get specific row
a[0,:] 

array([1, 2, 3, 4, 5, 6, 7])

In [31]:
#Get a specific col
a[:,3]

array([ 4, 11])

In [32]:
a[0,2:7:2]

array([3, 5, 7])

In [35]:
a[1,4]
a[1,4]= 19
print(a)



[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 19 13 14]]


In [39]:
#initializing different types of arrays

#All zeros matrix

np.zeros(4) 

#All ones matrix

np.ones((8,3))


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
#Any other number

np.full((2,3),88)

array([[88, 88, 88],
       [88, 88, 88]])

In [42]:
np.random.rand(2,3)

array([[0.07746211, 0.29270507, 0.7099853 ],
       [0.17005576, 0.90632832, 0.05941203]])

In [44]:
#Random Integer values

np.random.randint(6,size=(3,4))

array([[0, 3, 3, 0],
       [1, 3, 4, 4],
       [5, 2, 3, 5]])